# Stage 1 - BUILD DIST FILES
FROM node:20-alpine3.18 as node
WORKDIR /app
COPY . .
RUN npm install --legacy-peer-deps
RUN npm run build --configuration=production

# Stage 2 - BUILD IMAGE
FROM nginx:1.25-alpine
COPY --from=node /app/dist/recipe-app /usr/share/nginx/html
COPY --from=node /app/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
EXPOSE 80