apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key : label-value  
    spec:
      containers:
        - name: deploment-container-name
          image: docker.io/rosalitogabriel/recipe:v1
          env:
          - name: HELLO
            value: "World!"
          imagePullPolicy: Always
          ports:
          - containerPort: 80